// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akygrkonuqiywfadrrmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFreWdya29udXFpeXdmYWRycm1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NTAzMjAsImV4cCI6MjA1NzUyNjMyMH0.QFgb_dUmnJnpajrYBMXP2yB0wwSKEzo7bgknxCQk_w0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);